# Generated by Django 3.0.14 on 2022-02-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Registerations',
        ),
    ]
