# Generated by Django 3.0.14 on 2022-03-04 10:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=122)),
                ('To', models.CharField(max_length=122)),
                ('Subject', models.CharField(max_length=122)),
                ('Body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
