# Generated by Django 3.0.14 on 2022-03-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_emails',
            name='Team_Code',
            field=models.CharField(default=0, max_length=122),
        ),
    ]
