# Generated by Django 3.0.14 on 2022-03-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_emails_team_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
