# Generated by Django 3.0.14 on 2022-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='q1',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AddField(
            model_name='scores',
            name='q10',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AddField(
            model_name='scores',
            name='q2',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AddField(
            model_name='scores',
            name='q3',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AddField(
            model_name='scores',
            name='q4',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AddField(
            model_name='scores',
            name='q5',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AddField(
            model_name='scores',
            name='q6',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AddField(
            model_name='scores',
            name='q7',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AddField(
            model_name='scores',
            name='q8',
            field=models.CharField(blank=True, max_length=122),
        ),
        migrations.AddField(
            model_name='scores',
            name='q9',
            field=models.CharField(blank=True, max_length=122),
        ),
    ]
